### ISSUE TITLE
MongoDB setup

### ISSUE THREAD

**Issue by Pr0jectN1ne** [ZiraDiscord/Zira#4]
i keep getting this error ```[Cluster (Error)] MongoError: Authentication failed.```,i tried making a user and still dont work. Bot does come online and wont respond. i would like to get this working as it was a brilliant bot out there.thanks

**Comment by FireGamer3** [comment]
Be sure that you have mongo installed correctly and that the env variables on zira are correct as well

**Comment by Pr0jectN1ne** [comment]
okay ill try that and what do i add into the db?

**Comment by FireGamer3** [comment]
Really all you need to do is create a database for all of the zira stuff to be in. You will need to create a user for that database so that your instance of zira can access it finally you will need to make sure that you env variables match your database. Once done correctly zira should automatically create the collections that are needed in the database

**Comment by Pr0jectN1ne** [comment]
thanks for your help and ill try it soon
